trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
# 1. Instalar Node.js
- task: NodeTool@0
  inputs:
    versionSpec: '20.x'
  displayName: 'Install Node.js'

# 2. Instalar dependencias y construir el proyecto
- script: |
    npm install -g @angular/cli
    npm install
    ng build --prod
  displayName: 'Install npm packages and build Angular project'

# 3. Ejecutar pruebas (unitarias o e2e)
- script: |
    npm run test
  displayName: 'Run tests'

# 4. Publicar artefactos (compilados del proyecto)
- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: 'dist'
    artifactName: 'drop'
    publishLocation: 'Container'
  displayName: 'Publish build artifacts'
